#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Formatting only staged files\n"
nr precommit

echo "Checking lint errors on staged files\n"
nr lint --cache

if [ $? -ne 0 ]; then
    echo "Lint error\n"
    exit 1
fi